Frontend V0.1
emotz/enotgame pull request #16
Opened 2017-04-25 17:06 UTC by ITarako

2017-04-26 08:12 UTC, ITarako commented
проглядел внезапный lunch await,  буду доделывать

2017-04-26 10:06 UTC, Eoksni commented
Убери bundle из репы.
Никогда не коммить скомпилированный код или зависимости (node_modules).
И засунь этот бандл в отдельную папку, например frontend/dist.

2017-04-30 06:00 UTC, Eoksni commented on frontend/lib/main.js
> +import front from './front-enot.js';
`'../../game/lib/huyengine.js'` не очень красиво
Замути алиас https://webpack.js.org/configuration/resolve/
Чтобы 
```js
import engine from '../../game/lib/huyengine.js';
```
Превратился в 
```js
import engine from 'game/huyengine.js';
```

2017-05-04 18:29 UTC, Eoksni requested changes
Добавил eslint и файл настроек к нему. Пробегись по всем файлам и поправь все на что он ругается. И заодно alt-shift-f.

А, да, в целом все отлично. Ни одного серьезного косяка, так, по мелочи. Разве что захардкоженный id это плохо, да и то не особо. А! Потерянные импорты это не хорошо. Я хз как оно у тебя работает и откуда берет engine в компонентах, но весь смысл импорта в том чтобы явно декларировать свои зависимости. Это помогает читать код как людям, так и всяким vscode'ам для автодополнения.

2017-05-04 18:29 UTC, Eoksni commented on README.md
> +```
Поставь линтер для маркдауна https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
и поправь в соответствии с ним.

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-create.vue
> +        <div id="create">
Нехорошо использовать захардкоженный id внутри компонента. Если ты создашь второй такой же компонент на странице, у них у обоих будут разные html элементы с одним и тем же id, это будет невалидный html.

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-create.js
> +    }
Засунь папку components в lib. Это все-таки часть нашего js кода, не дело ей болтаться снаружи.

2017-05-04 18:29 UTC, Eoksni commented on frontend/lib/main.js
> +}
Зачем ты что-то здесь экспортишь? Не предполагается, что твой main.js будет где-то импортироваться, не? И раз уж ты все равно экспортишь все что есть, это можно сделать проще
```js
export * from 'game/huyengine.js'
```

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-enot.vue
> +</template>
=== вместо ==

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-enot.js
> +            this.world = engine.lunch_buy(this.world, age.min, age.max);
а где import engine?

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-create.vue
> +                </div>
Не, `v-on:keyup.enter` это нехорошо. Лучше добавь watch на `min_age` и в нем меняй `max_age` вместо этого `age_control`. И наоборот соответственно.

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.vue
> +    <div v-bind:class="{'night':(world.environment.time%24 >=12)}">
эй, у димана же отдельный модуль для работы со временем есть, почему ты его не используешь?

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.vue
> +                <span v-if="enot.hungry=='голоден'">Enot is hungry!<br></span>
===

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.js
> +            new_world: {},
А зачем тебе `new_world`, есть же `world`? "И целого мира мало" &copy; ?

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.js
> +        enot: function () {
Computed свойства лучше называть так, чтобы было более-менее понятно что они computed, или чтобы было понятно их назначение. В данном случае я бы назвал `enot_to_display` или что-то в этом роде.

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.js
> +            this.$emit('create');
А что за событие `create`? Не нашел где оно emit'ится.

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.js
> +            this.new_world = engine.lunch_feed(this.world);
import engine?

2017-05-04 18:29 UTC, Eoksni commented on frontend/package.json
> +    "components":"components"
https://docs.npmjs.com/files/package.json#directories
Помоему не стоит сюда каждую директорию пихать. Лишние сложности с дальнейшим мейнтейном, да и непонятно нахера это надо :). Хотя хз, я не особо в курсе как тут все принято в ноде. Будет здорово если ты поизучаешь вопрос "как по феншую составлять package.json" и поделишься со мной, потому что мне все время лень этим заняться :)

2017-05-04 18:29 UTC, Eoksni commented on frontend/webpack.config.js
> +        library: 'engine'
А что `library` делает? Зачем оно?

2017-05-04 18:29 UTC, Eoksni commented on frontend/components/eg-ready.js
> +            this.$emit('create');
Наверное, осталось после геймовера ?

2017-05-09 10:32 UTC, ITarako commented on frontend/components/eg-ready.js
> +            new_world: {},
Переименовал в `tmp_world`. Сохраняю сюда результат feed/play/wait, чтобы затем использовать `compare`

2017-05-09 10:34 UTC, ITarako commented on frontend/webpack.config.js
> +        library: 'engine'
уже низачем ^_^

2017-05-09 10:35 UTC, ITarako commented
можно ревьювить

2017-05-10 11:01 UTC, Eoksni requested changes
eslint

2017-05-10 11:01 UTC, Eoksni commented on frontend/lib/components/eg-ready.js
> +            tmp_world: {},
сделать локальной для функции

2017-05-10 11:01 UTC, Eoksni commented on game/lib/huyengine.js
> +    clone
можно было просто заимпортить huyutility в нужных местах... ну да пофиг
![8052123](https://cloud.githubusercontent.com/assets/2010503/25895454/25369f64-35aa-11e7-903b-1262961e7d99.jpg)

2017-05-10 21:36 UTC, merged