Superenot
emotz/enotgame pull request #9
Opened 2017-04-06 10:52 UTC by Tekukatetetomo

enowait

2017-04-18 10:34 UTC, Eoksni commented
Посмотри на #10

2017-04-18 10:43 UTC, Eoksni commented
В enot_buy в случае ошибки возвращай нормальный текст ошибки а не huy.

2017-04-18 10:46 UTC, Eoksni commented
Сделай alt-shift-f (форматирование) для всех файлов

2017-04-18 11:02 UTC, Eoksni commented
Перенеси тесты в отдельную папку `test`

2017-04-18 11:04 UTC, Eoksni commented
Добавь тесты для `choosevent`

2017-04-18 11:09 UTC, Eoksni requested changes
лалала

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
>   */
Это дока к чему?

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> + * вероятность происхождения события указана в разделе enotevents.
"описняны" опечатка

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> + * @param {Enot} enot
Не пиши описание возвращаемого значения словами, используй `@returns`

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
>  function enot_feed(enot) {
Добавь @returns

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
>      }
Добавь @typedef для ComparEnot

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> + */
Добавь @returns

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> + */
укажи тип у enotdva параметра

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> + * @param {*} enotdva сравниваемый енот номер дваз
тип enot должен быть с Большой буквы

2017-04-18 11:09 UTC, Eoksni commented on game/enot.js
> +        }
Добавь подчеркивание между словами в resultenot - result_enot

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
Добавь `@returns`, 
Это не "вероятность происхождения события", а вес вероятности. И `происхождение события` это какая-то стремная формулировка.

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
И тип параметра enot должен быть с большой буквы

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
добавь `@returns`

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
И тип параметра enot должен быть с большой буквы

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
добавь `@returns`
И тип параметра enot должен быть с большой буквы

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> + */
добавь `@returns`
И тип параметра enot должен быть с большой буквы

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> +function choosevent() {
добавь `@returns`

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> +function choosevent() {
`прнципу` опечатка

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> +function choosevent() {
`обьекста` опечатка

2017-04-18 11:09 UTC, Eoksni commented on game/enotevents.js
> +function choosevent() {
добавь `@throws`
http://usejsdoc.org/tags-throws.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> + * @property environment
используй `@typedef` 
http://usejsdoc.org/tags-typedef.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> + * Время нашей енотовой планеты, оно неизменно мы над ним невластны.мы ваще все дно.
`world` и `environment` это типы, должны быть с заглавной буквы

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> +function init() {
добавь доку для `init`

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> + * @param {integer} min_age Минимальный возраст енота(должен быть указан пользователем, поидее)
Вместо `{object}` пиши `{Environment}`

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> + * @param {integer} min_age Минимальный возраст енота(должен быть указан пользователем, поидее)
И укажи для min_age и max_age включительно или нет

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> + * @param {integer} min_age Минимальный возраст енота(должен быть указан пользователем, поидее)
И добавь ссылку на `enot_buy` используя `@see~ или `@link`
http://usejsdoc.org/tags-see.html
http://usejsdoc.org/tags-inline-link.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> +function lunch_feed(world) {
добавь `@returns`
поменяй тип у world

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> +function lunch_feed(world) {
И добавь ссылку на enot_feed используя `@see` или `@link`
http://usejsdoc.org/tags-see.html
http://usejsdoc.org/tags-inline-link.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> +function lunch_play(world){
добавь `@returns`
поменяй тип у world
И добавь ссылку на enot_play используя `@see` или `@link`
http://usejsdoc.org/tags-see.html
http://usejsdoc.org/tags-inline-link.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyengine.js
> +    let res = {};
добавь `@returns`
поменяй тип у world
И добавь ссылку на enot_wait используя `@see` или `@link`
http://usejsdoc.org/tags-see.html
http://usejsdoc.org/tags-inline-link.html

2017-04-18 11:09 UTC, Eoksni commented on game/huyutility.js
> + */
enot с большой буквы, `@returns`

2017-04-18 11:09 UTC, Eoksni commented on game/huyutility.js
> + */
поставь тип `{Object}`

2017-04-18 11:09 UTC, Eoksni commented on game/huyutility.js
> + */
intger опечатка

2017-04-18 11:09 UTC, Eoksni commented on game/huyutility.js
> + */
добавь @returns

2017-04-18 11:09 UTC, Eoksni commented on game/time.js
>          is_nighttime: is_nighttime
добавь доку к is_daytime is_nighttime

2017-04-18 11:09 UTC, Eoksni commented on game/engine.test.js
> +let engine = require('./huyengine.js');
название тест файла должно соответствовать тестируемому модулю. Или переименуй тест в huyengine.test.js или huyengine.js в engine.js

2017-04-18 11:09 UTC, Eoksni commented on game/engine.test.js
> +}
функция `testo` у тебя повторяется в каждом тест файле. Вынеси ее в отдельный модуль `test-helpers.js`

2017-04-18 11:09 UTC, Eoksni commented on game/engine.test.js
> +        testo (res.environment.time !== undefined);
тест фейлится 
![image](https://cloud.githubusercontent.com/assets/2010503/25127857/b5659d9c-2461-11e7-9872-1a1fbbf16a20.png)

2017-04-18 11:09 UTC, Eoksni commented on game/engine.test.js
> +            enot: enot_buy(1, rnjesus)
у тебя в каждом тесте идет let world = блабла
Этот повторяющийся код вынеси в отдельную функцию init_world здесь же в этом файле.

2017-04-18 11:19 UTC, Tekukatetetomo commented on game/enot.js
>   */
эту доку писал ты, и я хз зачем, сам разбирайся!
ПоННЯЛ!?)

2017-04-18 11:37 UTC, Eoksni commented on game/enot.js
>   */
хуёнял

2017-04-18 12:09 UTC, Tekukatetetomo commented on game/enotevents.js
> +function choosevent() {
опчтка - ОПЕЧАТКА!

2017-04-18 12:11 UTC, Eoksni commented on game/enotevents.js
> +function choosevent() {
пожалуйста, поменял

2017-04-21 10:00 UTC, Eoksni approved these changes
@ITarako посмотри тоже, если все ок отпишись я замержу.

2017-04-21 10:09 UTC, merged